name: restaurant_app
description: Qpro - App móvil para meseros
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.1
  http: ^1.1.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  
  # Firebase para notificaciones
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9

  # Vibración y sonido
  audioplayers: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  